<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE QLSP[
	<!ELEMENT QLSP (SanPham*)>
	<!ELEMENT SanPham (TenHang, SoLuong, DonGia)>
	<!ATTLIST SanPham MaHang ID #REQUIRED>
	<!ELEMENT TenHang (#PCDATA)>
	<!ELEMENT SoLuong (#PCDATA)>
	<!ELEMENT DonGia (#PCDATA)>
]>
<QLSP>
  <SanPham MaHang="SP01">
    <TenHang>BimBim</TenHang>
    <SoLuong>2</SoLuong>
    <DonGia>10000</DonGia>
  </SanPham>
  <SanPham MaHang="SP02">
    <TenHang>Bánh</TenHang>
    <SoLuong>3</SoLuong>
    <DonGia>30000</DonGia>
  </SanPham>
  <SanPham MaHang="SP03">
    <TenHang>Mì tôm</TenHang>
    <SoLuong>2</SoLuong>
    <DonGia>10000</DonGia>
  </SanPham>
</QLSP>