=== Khanhnnguyend/XML_BTL/XML_BTL/qlnv.dtd
<!ELEMENT QLNV (Nhanvien*)>
<!ELEMENT Nhanvien (Hoten, Diachi, Gioitinh, Namsinh, Sdt, Password)>
<!ELEMENT Hoten (#PCDATA)>
<!ELEMENT Diachi (#PCDATA)>
<!ELEMENT Gioitinh (#PCDATA)>
<!ELEMENT Namsinh (#PCDATA)>
<!ELEMENT Sdt (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ATTLIST Nhanvien MaNV ID #REQUIRED>

=== Khanhnnguyend/XML_BTL/XML_BTL/QLnhanvien.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE QLNV SYSTEM "qlnv.dtd"[]>
<QLNV>
  <Nhanvien MaNV="NV01">
    <Hoten>huy</Hoten>
    <Diachi>tn</Diachi>
    <Gioitinh>nam</Gioitinh>
    <Namsinh>2002</Namsinh>
    <Sdt>0969578553</Sdt>
  </Nhanvien>
  <Nhanvien MaNV="NV02">
    <Hoten>huy2</Hoten>
    <Diachi>tn</Diachi>
    <Gioitinh>nam</Gioitinh>
    <Namsinh>2002</Namsinh>
    <Sdt>023244</Sdt>
  </Nhanvien>
  <Nhanvien MaNV="NV03">
    <Hoten>HUy</Hoten>
    <Diachi>tn</Diachi>
    <Gioitinh>nam</Gioitinh>
    <Namsinh>2002</Namsinh>
    <Sdt>20405530</Sdt>
  </Nhanvien>

</QLNV>
